# Don't forget to change .hound.yml

LineLength:
  Max: 120

StringLiterals:
  EnforcedStyle: single_quotes

DotPosition:
  EnforcedStyle: trailing

AsciiComments:
  Enabled: false

MethodLength:
  CountComments: false
  Max: 100

# Disabled while Gem stills support ruby 1.8
HashSyntax:
  Enabled: false
